server:
  port: 7777
  context-path:

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/team-platform
    username: team
    password: platform

  jpa:
    properties.hibernate.dialect:
    hibernate.ddl-auto: create
    show-sql: true
    format-sql: true
