server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:

  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: create
    show-sql: true
    format-sql: true

security:
  oauth2:
    client:
      client-id: kassad
      client-secret: kassad
    authorization:
      check-token-access: isAuthenticated()
logging:
  level:
    org:
      springframework:
        web: DEBUG
        security: DEBUG

