INSERT INTO USER VALUES (1 , 'user', '{noop}user', 'ADMIN');
INSERT INTO USER VALUES (2 , 'user5', '{bcrypt}$2a$04$TaCiyKj4/F2QFJqUT2F8pOj/Gz70PBsBF/a7ihYyNQwsSquxjJBw6', 'ADMIN');
INSERT INTO USER VALUES (3 , 'user1', '{null}user1', 'ADMIN');
INSERT INTO USER VALUES (4 , 'user2', 'user2', 'ADMIN');
INSERT INTO USER VALUES (5 , 'user3', '{noop}user3', 'ADMIN');

INSERT INTO TEAM_BOARD VALUES (1 ,'board 1',1);
INSERT INTO TEAM_BOARD VALUES (2 ,'board 2',2);
INSERT INTO TEAM_BOARD VALUES (3 ,'board 3',2);
INSERT INTO TEAM_BOARD VALUES (4 ,'board 4',1);
--INSERT INTO USER_EVENT VALUES (1 , '2019-04-01', 'description1', 'VACATION', 1);
--INSERT INTO USER_EVENT VALUES (2 , '2019-05-07', 'description2', 'SICKNESS', 2);
--INSERT INTO USER_EVENT VALUES (3 , '2019-05-03', 'description3', 'WORK_FROM_HOME', 1);
--INSERT INTO USER_EVENT VALUES (4 , '2019-04-09', 'description4', 'SICKNESS', 3);
--INSERT INTO USER_EVENT VALUES (5 , '2019-05-02', 'description5', 'VACATION', 2);
--INSERT INTO USER_EVENT VALUES (6 , '2019-01-04', 'description6', 'WORK_FROM_HOME', 1);