export enum UserEventType {
  VACATION = "VACATION",
  TRAINING = "TRAINING",
  SICKNESS = "SICKNESS",
  BUSINESS_TRIP = "BUSINESS_TRIP",
  WORK_FROM_HOME = "WORK_FROM_HOME" ,
  OTHER = "OTHER",
  NO_EVENT = "NO_EVENT"
}
